import re
from pathlib import Path
from typing import Iterable


class ProgressReportBuilder:
    @staticmethod
    def strip_dsml_blocks(text: str) -> str:
        if not isinstance(text, str):
            return ""

        cleaned = text
        # Remove full DSML tool call blocks generated by bridge output.
        cleaned = re.sub(
            r"<｜DSML｜tool_calls>[\s\S]*?</｜DSML｜tool_calls>",
            "",
            cleaned,
            flags=re.IGNORECASE,
        )
        # Remove remaining single-line DSML tags if any.
        cleaned = re.sub(r"^\s*<｜DSML｜[^\n]*$", "", cleaned, flags=re.IGNORECASE | re.MULTILINE)
        return cleaned.strip()

    @staticmethod
    def shorten_text(text: str, limit: int = 240) -> str:
        normalized = " ".join(text.split())
        if len(normalized) <= limit:
            return normalized
        return normalized[: limit - 1] + "…"

    @staticmethod
    def extract_final_block(text: str) -> str:
        if not isinstance(text, str):
            return ""

        cleaned = ProgressReportBuilder.strip_dsml_blocks(text)
        matches = re.findall(r"\[star\][\s\S]*?\[TERMINATE\]", cleaned)
        if matches:
            return matches[-1].strip()

        return cleaned.strip()

    @staticmethod
    def agent_section_title(agent_name: str) -> str:
        mapping = {
            "env_setup_agent": "环境设置",
            "protein_pre_agent": "蛋白质处理",
            "ligand_pre_agent": "配体处理",
            "dock_agent": "分子对接",
            "memory_agent": "执行摘要",
        }
        return mapping.get(agent_name, agent_name)

    @staticmethod
    def load_progress_report(path: Path) -> str:
        try:
            if path.exists():
                content = path.read_text(encoding="utf-8").strip()
                if content:
                    return content
        except OSError:
            pass

        return (
            "[star]\n"
            "## 工作进度\n"
            "- 当前还没有可用的历史进度记录。\n"
            "## 执行摘要\n"
            "- 尚未开始。\n"
            "[TERMINATE]"
        )

    @classmethod
    def build_progress_report(cls, raw_task: str, transcript: list[tuple[str, str]]) -> str:
        latest_by_agent: dict[str, str] = {}
        for source, content in transcript:
            if source in {"user", "system", "Coordinator"}:
                continue
            latest_by_agent[source] = content

        order = ["env_setup_agent", "protein_pre_agent", "ligand_pre_agent", "dock_agent", "memory_agent"]
        lines = ["[star]", "## 原始任务", raw_task, ""]

        if not latest_by_agent:
            lines.extend([
                "## 当前进度",
                "- 当前还没有收到可归档的 agent 结果。",
                "",
                "## 说明",
                "- 此文件由 main.py 在运行过程中持续更新，并作为后续 Coordinator 决策上下文。",
                "[TERMINATE]",
            ])
            return "\n".join(lines)

        for agent_name in order:
            content = latest_by_agent.get(agent_name)
            if not content:
                continue
            section_title = cls.agent_section_title(agent_name)
            final_block = cls.extract_final_block(content)
            lines.append(f"## {section_title}")
            lines.append(final_block)
            lines.append("")

        lines.extend([
            "## 说明",
            "- 此文件由 main.py 在运行过程中持续更新，并作为后续 Coordinator 决策上下文。",
            "[TERMINATE]",
        ])
        return "\n".join(lines)

    @classmethod
    def save_progress_report(cls, path: Path, raw_task: str, transcript: list[tuple[str, str]]) -> None:
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(cls.build_progress_report(raw_task, transcript), encoding="utf-8")
        except OSError:
            return

    @classmethod
    def build_final_report(cls, raw_task: str, transcript: list[tuple[str, str]]) -> str:
        lines = [
            "===== 最终执行报告 =====",
            "任务输入：",
            raw_task,
            "",
            f"已记录消息数：{len(transcript)}",
            "",
            "执行摘要：",
        ]

        if not transcript:
            lines.append("- 本次没有收到可显示的 agent 文本消息。")
        else:
            for index, (source, content) in enumerate(transcript, start=1):
                lines.append(f"{index}. {source}: {cls.shorten_text(content)}")

        lines.append("")
        lines.append("说明：上面的终端输出保留了完整中间过程，这里只给出系统性摘要。")
        return "\n".join(lines)
